version: '3.8'
services:
  frontend:
    build:
      context: .
      dockerfile: commission-plan-simulator/Dockerfile
    ports:
      - '3000:80'
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - db
  db:
    image: postgres
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
