# version: '3.8'
# services:
#   frontend:
#     build:
#       context: .
#       dockerfile: frontend/Dockerfile
#     ports:
#       - '3000:80'
#     depends_on:
#       - backend
#   backend:
#     build:
#       context: .
#       dockerfile: backend/Dockerfile
#     ports:
#       - '3001:3000'
#     environment:
#       - NODE_ENV=production
#     volumes:
#       - ./backend:/usr/src/app
#     depends_on:
#       - db
#   db:
#     image: postgres
#     environment:
#       POSTGRES_DB: mydatabase
#       POSTGRES_USER: postgres
#       POSTGRES_PASSWORD: password
#     ports:
#       - '5432:5432'

version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://prisma:prisma@db:5432/prismadb?schema=public
    depends_on:
      - db
    networks:
      - app-network

  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: prisma
      POSTGRES_PASSWORD: prisma
      POSTGRES_DB: prismadb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres-data:
